# Generated by Django 2.1.5 on 2019-01-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('phone', models.CharField(max_length=10, verbose_name='telefone')),
                ('cell', models.CharField(max_length=11, verbose_name='celular')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('cnpj', models.CharField(max_length=14, verbose_name='cnpj')),
                ('cep', models.CharField(max_length=8, verbose_name='cep')),
                ('ncm', models.CharField(max_length=8, verbose_name='ncm')),
                ('isbn', models.CharField(max_length=13, verbose_name='isbn')),
            ],
            options={
                'verbose_name': 'dado pessoal',
                'verbose_name_plural': 'dados pessoais',
                'ordering': ['first_name'],
            },
        ),
    ]
