# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='rg',
            field=models.CharField(default=1, max_length=7, verbose_name='rg'),
            preserve_default=False,
        ),
    ]
