# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personaldata_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='rg',
            field=models.CharField(max_length=10, verbose_name='rg'),
        ),
    ]
